### PR TITLE
Added step classes to step and backdrop divs

### LINKED ISSUE #40: Custom class for step and backdrop
In my project I have a problem where I need to customize css for some specific step.
Currently there are no step specific classes for step holder and backdrop root.

My proposition is to add something like `joyride-step-stepName` and `backdrop-stepName` so we can customize styling for specific step. As step names are unique, this should'nt be a problem

### PR DESCRIPTION
**Pull request by j0shko**
Closes #40

### CODE REVIEW

**Comment by tnicola** [comment]
Hi @j0shko , 
The PR is fine, thanks for contributing! Could you please add a couple of unit tests to check the class is added correctly in both the component and the backdrop? Also, the build is not passing since a unit test is failing. 

If you want I can do all the modifications.

**Comment by j0shko** [comment]
Hi @tnicola ,
Thank you for the quick response. 😄 
I'll add tests and fix the build, it's not a problem.

**Comment by j0shko** [comment]
Hi @tnicola, 
I switched from classes to ids, and added tests. Can you please check if tests are in correct place?

**Comment by tnicola** [comment]
Everything's fine, merged!Thanks @j0shko !

**Comment by tnicola** [comment]
Released in the new version 2.2.8.

**Pull request merged**
