### PR TITLE
Updated to meet angular 10 requirements

### PR DESCRIPTION
**Pull request by alexsukhodolsky**
@tnicola please review -- I updated the angular dependencies to the latest version 9. I also pass in a generic type into `ModuleWithProviders`.

### CODE REVIEW

**Comment by tnicola** [comment]
Ehy @alexsukhodolsky , merged! Thanks!

**Comment by alexsukhodolsky** [comment]
thanks @tnicola! Can you please create a new release as well? Thanks!

**Comment by tnicola** [comment]
Released ngx-joyride@2.3.1 🚀

**Comment by eyalella** [comment]
To anyone looking at this, take this [repo](https://www.npmjs.com/package/ngx-joyride) and not the [other one](https://www.npmjs.com/package/@boxmeglobal/ngx-joyride/v/2.2.14-7), took me a while to understand why I was not seeing the versioned mentioned by @tnicola

**Pull request merged**
